app = 'hotefinder-spring-fog-8693'
primary_region = 'cdg'
console_command = '/rails/bin/rails console'

[build]
  [build.args]
    BUILD_COMMAND = "bin/rails fly:build"

[deploy]
  release_command = "bin/rails fly:release"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = "bin/rails server"

[env]
  PORT = "3000"